apps/cart/urls.py
from django.conf.urls import url

from apps.cart.views import CartAddView, CartInfoView, CartUpdateView, CartDeleteView

app_name = 'cart'

urlpatterns = [
    url(r'^add$', CartAddView.as_view(), name='add'),  # 购物车记录添加
    url(r'^$', CartInfoView.as_view(), name='show'),  # 购物车页面
    url(r'^update$', CartUpdateView.as_view(), name='update'),  # 购物车记录更新
    url(r'^delete$', CartDeleteView.as_view(), name='delete'),  # 购物车记录删除

]

apps/goods/urls.py
from django.conf.urls import url
from apps.goods.views import IndexView, DetailView, ListView

app_name = 'goods'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'),  # 详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'),  # 列表页

]

apps/user/urls.py
from django.conf.urls import url

from apps.user.views import RegisterView, ActiveView, LoginView, LogoutView,UserInfoView, UserOrderView, AddressView

from django.contrib.auth.decorators import login_required

app_name = 'user'

urlpatterns = [
    url(r'^register/', RegisterView.as_view(), name='register'),
    url(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout$',LogoutView.as_view(),name='logout'),

    # url(r'^$', login_required(UserInfoView.as_view()), name='user'),  # 用户中心-信息页
    # url(r'^order$', login_required(UserOrderView.as_view()), name='order'),  # 用户中心-订单页面
    # url(r'^address$', login_required(AddressView.as_view()), name='address'),  # 用户中心-地址页面

    url(r'^$', UserInfoView.as_view(), name='user'),  # 用户中心-信息页
    url(r'^order$', UserOrderView.as_view(), name='order'),  # 用户中心-订单页面
    url(r'^address$', AddressView.as_view(), name='address'),  # 用户中心-地址页面
]

dailyfresh/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),  # 富文本编辑器
    url(r'^search/', include('haystack.urls')),  # 全文检索框架
    url(r'^user/', include('apps.user.urls', namespace='user')),  # 用户模块
    url(r'^', include('apps.goods.urls', namespace='goods')),  # 商品模块
    url(r'^cart/', include('apps.cart.urls', namespace='cart')),  # 购物车模块
    url(r'^order/', include('apps.order.urls', namespace='order'))  # 订单模块

]

templates/base.html
{# 登录、注册 首页 #}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题 #}
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>
    {# 网页顶部引入文件块 #}
    {% block topfiles %}{% endblock %}
</head>
<body>

{# 网页顶部欢迎信息 #}
{% block header_con %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜</div>
            <div class="fr">
                {% if user.is_authenticated %}
                    <div class="login_btn fl">
                        欢迎您:<em><a href="{% url 'user:user' %}">{{ user.username }}</a></em>
                        <span>|</span>
                        <a href="{% url 'user:logout' %}">退出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
                    </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:user' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:show' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'user:order' %}">我的订单</a>
                </div>
            </div>

        </div>
    </div>
{% endblock %}


{# 网页搜索框块 #}
{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="#" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="search_con fl">
            <form action="/search" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>

        </div>
        {% block cart_bar %}
            <div class="guest_cart fr">
                <a href="#" class="cart_name fl">我的购物车</a>
                {% if cart_count %}
                    <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
                {% else %}
                    <div class="goods_count fl" id="show_count">0</div>
                {% endif %}
            </div>
        {% endblock %}

    </div>
{% endblock search_bar %}


{# 网页主体内容块 #}
{% block body %}{% endblock %}


<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>opyRight © 2019-2020 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>

    {# 网页底部html元素块 #}
    {% block bottom %}
    {% endblock bottom %}

    {# 网页底部引入文件块 #}
    {% block bottomfiles %}
    {% endblock bottomfiles %}

</div>

</body>
</html>

templates/base_detail_list.html
{# 详情页、列表页 #}
{% extends 'base.html' %}

{# 网站主体内容块 #}
{% block body %}
    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">
                    {% for type in types %}
                        <li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <ul class="navlist fl">
                <li><a>首页</a></li>
                <li>|</li>
                <li><a>手机生鲜</a></li>
                <li>|</li>
                <li><a>抽奖</a></li>
            </ul>
        </div>
    </div>
    {# 详情页，列表页主体内容块 #}
    {% block main_content %}{% endblock %}
{% endblock %}

templates/base_no_cart.html
{# 购物车、提交订单 #}

{% extends 'base.html' %}
{% load staticfiles %}
{# 网页顶部搜索框块 #}
{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="#" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="sub_page_name fl"></div>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
        <div class="search_con fr">
            <form action="/search" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
    </div>
{% endblock %}

templates/base_user_center.html
{# 用户中心3页面 #}

{% extends 'base_no_cart.html' %}
{% block title %}
    天天生鲜-用户中心
{% endblock %}

{% block page_title %}
    用户中心
{% endblock %}

{% block body %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:user' %}" {% if page == 'user' %} class="active"{% endif %}>· 个人信息</a></li>
                <li><a href="{% url 'user:order' %}" {% if page == 'order' %} class="active" {% endif %}>· 全部订单</a></li>
                <li><a href="{% url 'user:address' %}" {% if page == 'address' %} class="active"{% endif %}>· 收获地址</a>
                </li>
            </ul>
        </div>
        {# 用户中心右侧内容 #}
        {% block right_content %}

        {% endblock %}
    </div>

{% endblock body %}

templates/static_base.html
{# 登录、注册 首页 #}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题 #}
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>
    {# 网页顶部引入文件块 #}
    {% block topfiles %}{% endblock %}
</head>
<body>

{# 网页顶部欢迎信息 #}
{% block header_con %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜</div>
            <div class="fr">

                <div class="login_btn fl">
                    <a href="{% url 'user:login' %}">登录</a>
                    <span>|</span>
                    <a href="{% url 'user:register' %}">注册</a>
                </div>

                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:user' %}">用户中心</a>
                    <span>|</span>
                    <a href="#">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'user:order' %}">我的订单</a>
                </div>
            </div>

        </div>
    </div>
{% endblock %}


{# 网页搜索框块 #}
{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="#" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="search_con fl">
            <form action="#" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_text fl" name="" value="搜索">
            </form>

        </div>
        {% block cart_bar %}
            <div class="guest_cart fr">
                <a href="#" class="cart_name fl">我的购物车</a>
                {% if cart_count %}
                    <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
                {% else %}
                    <div class="goods_count fl" id="show_count">0</div>
                {% endif %}
            </div>
        {% endblock %}

    </div>
{% endblock search_bar %}


{# 网页主体内容块 #}
{% block body %}{% endblock %}


<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>opyRight © 2019-2020 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>

    {# 网页底部html元素块 #}
    {% block bottom %}
    {% endblock bottom %}

    {# 网页底部引入文件块 #}
    {% block bottomfiles %}
    {% endblock bottomfiles %}

</div>

</body>
</html>